use doctor::cloc::LanguageType;
use napi_derive::napi;

#[derive(Debug)]
#[napi(string_enum)]
pub enum JsLanguageType {
  ABNF,
  Abap,
  ActionScript,
  Ada,
  Agda,
  Alex,
  Alloy,
  Arduino,
  AsciiDoc,
  Asn1,
  Asp,
  AspNet,
  Assembly,
  AssemblyGAS,
  AutoHotKey,
  Autoconf,
  Automake,
  Bash,
  Batch,
  Bean,
  BrightScript,
  C,
  CHeader,
  CMake,
  CSharp,
  CShell,
  Cabal,
  Cassius,
  Ceylon,
  Clojure,
  ClojureC,
  ClojureScript,
  Cobol,
  CodeQL,
  CoffeeScript,
  Cogent,
  ColdFusion,
  ColdFusionScript,
  Coq,
  Cpp,
  CppHeader,
  Crystal,
  Css,
  D,
  Daml,
  Dart,
  DeviceTree,
  Dhall,
  Dockerfile,
  DotNetResource,
  DreamMaker,
  Dust,
  Edn,
  Elisp,
  Elixir,
  Elm,
  Elvish,
  EmacsDevEnv,
  Emojicode,
  Erlang,
  FEN,
  FSharp,
  Fish,
  FlatBuffers,
  Forth,
  FortranLegacy,
  FortranModern,
  FreeMarker,
  Fstar,
  Futhark,
  GDB,
  GdScript,
  Gherkin,
  Gleam,
  Glsl,
  Go,
  Gohtml,
  Graphql,
  Groovy,
  Gwion,
  Hamlet,
  Handlebars,
  Happy,
  Haskell,
  Haxe,
  Hcl,
  Headache,
  Hex,
  Hlsl,
  HolyC,
  Html,
  Idris,
  Ini,
  IntelHex,
  Isabelle,
  Jai,
  Java,
  JavaScript,
  Json,
  Jsonnet,
  Jsx,
  Julia,
  Julius,
  Jupyter,
  K,
  KakouneScript,
  Kotlin,
  LLVM,
  Lean,
  Less,
  LinkerScript,
  Liquid,
  Lisp,
  LiveScript,
  Logtalk,
  Lua,
  Lucius,
  Madlang,
  Makefile,
  Markdown,
  Meson,
  Mint,
  ModuleDef,
  MoonScript,
  MsBuild,
  Mustache,
  Nim,
  Nix,
  NotQuitePerl,
  OCaml,
  ObjectiveC,
  ObjectiveCpp,
  Odin,
  OpenType,
  Org,
  Oz,
  PSL,
  Pan,
  Pascal,
  Perl,
  Perl6,
  Pest,
  Php,
  Polly,
  Pony,
  PostCss,
  PowerShell,
  Processing,
  Prolog,
  Protobuf,
  Pug,
  PureScript,
  Python,
  Q,
  Qcl,
  Qml,
  R,
  RON,
  RPMSpecfile,
  Racket,
  Rakefile,
  Razor,
  ReStructuredText,
  Renpy,
  Ruby,
  RubyHtml,
  Rust,
  SRecode,
  Sass,
  Scala,
  Scheme,
  Scons,
  Sh,
  Sml,
  Solidity,
  SpecmanE,
  Spice,
  Sql,
  Stan,
  Stratego,
  Stylus,
  Svelte,
  Svg,
  Swift,
  Swig,
  SystemVerilog,
  Tcl,
  Tera,
  Tex,
  Text,
  Thrift,
  Toml,
  Tsx,
  Ttcn,
  Twig,
  TypeScript,
  UnrealDeveloperMarkdown,
  UnrealPlugin,
  UnrealProject,
  UnrealScript,
  UnrealShader,
  UnrealShaderHeader,
  UrWeb,
  UrWebProject,
  VB6,
  VBScript,
  Vala,
  Velocity,
  Verilog,
  VerilogArgsFile,
  Vhdl,
  VimScript,
  VisualBasic,
  VisualStudioProject,
  VisualStudioSolution,
  Vue,
  WebAssembly,
  Wolfram,
  XSL,
  Xaml,
  XcodeConfig,
  Xml,
  Xtend,
  Yaml,
  Zig,
  Zsh,
}

impl From<LanguageType> for JsLanguageType {
  fn from(language: LanguageType) -> Self {
    match language {
      LanguageType::ABNF => Self::ABNF,
      LanguageType::Abap => Self::Abap,
      LanguageType::ActionScript => Self::ActionScript,
      LanguageType::Ada => Self::Ada,
      LanguageType::Agda => Self::Agda,
      LanguageType::Alex => Self::Alex,
      LanguageType::Alloy => Self::Alloy,
      LanguageType::Arduino => Self::Arduino,
      LanguageType::AsciiDoc => Self::AsciiDoc,
      LanguageType::Asn1 => Self::Asn1,
      LanguageType::Asp => Self::Asp,
      LanguageType::AspNet => Self::AspNet,
      LanguageType::Assembly => Self::Assembly,
      LanguageType::AssemblyGAS => Self::AssemblyGAS,
      LanguageType::AutoHotKey => Self::AutoHotKey,
      LanguageType::Autoconf => Self::Autoconf,
      LanguageType::Automake => Self::Automake,
      LanguageType::Bash => Self::Bash,
      LanguageType::Batch => Self::Batch,
      LanguageType::Bean => Self::Bean,
      LanguageType::BrightScript => Self::BrightScript,
      LanguageType::C => Self::C,
      LanguageType::CHeader => Self::CHeader,
      LanguageType::CMake => Self::CMake,
      LanguageType::CSharp => Self::CSharp,
      LanguageType::CShell => Self::CShell,
      LanguageType::Cabal => Self::Cabal,
      LanguageType::Cassius => Self::Cassius,
      LanguageType::Ceylon => Self::Ceylon,
      LanguageType::Clojure => Self::Clojure,
      LanguageType::ClojureC => Self::ClojureC,
      LanguageType::ClojureScript => Self::ClojureScript,
      LanguageType::Cobol => Self::Cobol,
      LanguageType::CodeQL => Self::CodeQL,
      LanguageType::CoffeeScript => Self::CoffeeScript,
      LanguageType::Cogent => Self::Cogent,
      LanguageType::ColdFusion => Self::ColdFusion,
      LanguageType::ColdFusionScript => Self::ColdFusionScript,
      LanguageType::Coq => Self::Coq,
      LanguageType::Cpp => Self::Cpp,
      LanguageType::CppHeader => Self::CppHeader,
      LanguageType::Crystal => Self::Crystal,
      LanguageType::Css => Self::Css,
      LanguageType::D => Self::D,
      LanguageType::Daml => Self::Daml,
      LanguageType::Dart => Self::Dart,
      LanguageType::DeviceTree => Self::DeviceTree,
      LanguageType::Dhall => Self::Dhall,
      LanguageType::Dockerfile => Self::Dockerfile,
      LanguageType::DotNetResource => Self::DotNetResource,
      LanguageType::DreamMaker => Self::DreamMaker,
      LanguageType::Dust => Self::Dust,
      LanguageType::Edn => Self::Edn,
      LanguageType::Elisp => Self::Elisp,
      LanguageType::Elixir => Self::Elixir,
      LanguageType::Elm => Self::Elm,
      LanguageType::Elvish => Self::Elvish,
      LanguageType::EmacsDevEnv => Self::EmacsDevEnv,
      LanguageType::Emojicode => Self::Emojicode,
      LanguageType::Erlang => Self::Erlang,
      LanguageType::FEN => Self::FEN,
      LanguageType::FSharp => Self::FSharp,
      LanguageType::Fish => Self::Fish,
      LanguageType::FlatBuffers => Self::FlatBuffers,
      LanguageType::Forth => Self::Forth,
      LanguageType::FortranLegacy => Self::FortranLegacy,
      LanguageType::FortranModern => Self::FortranModern,
      LanguageType::FreeMarker => Self::FreeMarker,
      LanguageType::Fstar => Self::Fstar,
      LanguageType::Futhark => Self::Futhark,
      LanguageType::GDB => Self::GDB,
      LanguageType::GdScript => Self::GdScript,
      LanguageType::Gherkin => Self::Gherkin,
      LanguageType::Gleam => Self::Gleam,
      LanguageType::Glsl => Self::Glsl,
      LanguageType::Go => Self::Go,
      LanguageType::Gohtml => Self::Gohtml,
      LanguageType::Graphql => Self::Graphql,
      LanguageType::Groovy => Self::Groovy,
      LanguageType::Gwion => Self::Gwion,
      LanguageType::Hamlet => Self::Hamlet,
      LanguageType::Handlebars => Self::Handlebars,
      LanguageType::Happy => Self::Happy,
      LanguageType::Haskell => Self::Haskell,
      LanguageType::Haxe => Self::Haxe,
      LanguageType::Hcl => Self::Hcl,
      LanguageType::Headache => Self::Headache,
      LanguageType::Hex => Self::Hex,
      LanguageType::Hlsl => Self::Hlsl,
      LanguageType::HolyC => Self::HolyC,
      LanguageType::Html => Self::Html,
      LanguageType::Idris => Self::Idris,
      LanguageType::Ini => Self::Ini,
      LanguageType::IntelHex => Self::IntelHex,
      LanguageType::Isabelle => Self::Isabelle,
      LanguageType::Jai => Self::Jai,
      LanguageType::Java => Self::Java,
      LanguageType::JavaScript => Self::JavaScript,
      LanguageType::Json => Self::Json,
      LanguageType::Jsonnet => Self::Jsonnet,
      LanguageType::Jsx => Self::Jsx,
      LanguageType::Julia => Self::Julia,
      LanguageType::Julius => Self::Julius,
      LanguageType::Jupyter => Self::Jupyter,
      LanguageType::K => Self::K,
      LanguageType::KakouneScript => Self::KakouneScript,
      LanguageType::Kotlin => Self::Kotlin,
      LanguageType::LLVM => Self::LLVM,
      LanguageType::Lean => Self::Lean,
      LanguageType::Less => Self::Less,
      LanguageType::LinkerScript => Self::LinkerScript,
      LanguageType::Liquid => Self::Liquid,
      LanguageType::Lisp => Self::Lisp,
      LanguageType::LiveScript => Self::LiveScript,
      LanguageType::Logtalk => Self::Logtalk,
      LanguageType::Lua => Self::Lua,
      LanguageType::Lucius => Self::Lucius,
      LanguageType::Madlang => Self::Madlang,
      LanguageType::Makefile => Self::Makefile,
      LanguageType::Markdown => Self::Markdown,
      LanguageType::Meson => Self::Meson,
      LanguageType::Mint => Self::Mint,
      LanguageType::ModuleDef => Self::ModuleDef,
      LanguageType::MoonScript => Self::MoonScript,
      LanguageType::MsBuild => Self::MsBuild,
      LanguageType::Mustache => Self::Mustache,
      LanguageType::Nim => Self::Nim,
      LanguageType::Nix => Self::Nix,
      LanguageType::NotQuitePerl => Self::NotQuitePerl,
      LanguageType::OCaml => Self::OCaml,
      LanguageType::ObjectiveC => Self::ObjectiveC,
      LanguageType::ObjectiveCpp => Self::ObjectiveCpp,
      LanguageType::Odin => Self::Odin,
      LanguageType::OpenType => Self::OpenType,
      LanguageType::Org => Self::Org,
      LanguageType::Oz => Self::Oz,
      LanguageType::PSL => Self::PSL,
      LanguageType::Pan => Self::Pan,
      LanguageType::Pascal => Self::Pascal,
      LanguageType::Perl => Self::Perl,
      LanguageType::Perl6 => Self::Perl6,
      LanguageType::Pest => Self::Pest,
      LanguageType::Php => Self::Php,
      LanguageType::Polly => Self::Polly,
      LanguageType::Pony => Self::Pony,
      LanguageType::PostCss => Self::PostCss,
      LanguageType::PowerShell => Self::PowerShell,
      LanguageType::Processing => Self::Processing,
      LanguageType::Prolog => Self::Prolog,
      LanguageType::Protobuf => Self::Protobuf,
      LanguageType::Pug => Self::Pug,
      LanguageType::PureScript => Self::PureScript,
      LanguageType::Python => Self::Python,
      LanguageType::Q => Self::Q,
      LanguageType::Qcl => Self::Qcl,
      LanguageType::Qml => Self::Qml,
      LanguageType::R => Self::R,
      LanguageType::RON => Self::RON,
      LanguageType::RPMSpecfile => Self::RPMSpecfile,
      LanguageType::Racket => Self::Racket,
      LanguageType::Rakefile => Self::Rakefile,
      LanguageType::Razor => Self::Razor,
      LanguageType::ReStructuredText => Self::ReStructuredText,
      LanguageType::Renpy => Self::Renpy,
      LanguageType::Ruby => Self::Ruby,
      LanguageType::RubyHtml => Self::RubyHtml,
      LanguageType::Rust => Self::Rust,
      LanguageType::SRecode => Self::SRecode,
      LanguageType::Sass => Self::Sass,
      LanguageType::Scala => Self::Scala,
      LanguageType::Scheme => Self::Scheme,
      LanguageType::Scons => Self::Scons,
      LanguageType::Sh => Self::Sh,
      LanguageType::Sml => Self::Sml,
      LanguageType::Solidity => Self::Solidity,
      LanguageType::SpecmanE => Self::SpecmanE,
      LanguageType::Spice => Self::Spice,
      LanguageType::Sql => Self::Sql,
      LanguageType::Stan => Self::Stan,
      LanguageType::Stratego => Self::Stratego,
      LanguageType::Stylus => Self::Stylus,
      LanguageType::Svelte => Self::Svelte,
      LanguageType::Svg => Self::Svg,
      LanguageType::Swift => Self::Swift,
      LanguageType::Swig => Self::Swig,
      LanguageType::SystemVerilog => Self::SystemVerilog,
      LanguageType::Tcl => Self::Tcl,
      LanguageType::Tera => Self::Tera,
      LanguageType::Tex => Self::Tex,
      LanguageType::Text => Self::Text,
      LanguageType::Thrift => Self::Thrift,
      LanguageType::Toml => Self::Toml,
      LanguageType::Tsx => Self::Tsx,
      LanguageType::Ttcn => Self::Ttcn,
      LanguageType::Twig => Self::Twig,
      LanguageType::TypeScript => Self::TypeScript,
      LanguageType::UnrealDeveloperMarkdown => Self::UnrealDeveloperMarkdown,
      LanguageType::UnrealPlugin => Self::UnrealPlugin,
      LanguageType::UnrealProject => Self::UnrealProject,
      LanguageType::UnrealScript => Self::UnrealScript,
      LanguageType::UnrealShader => Self::UnrealShader,
      LanguageType::UnrealShaderHeader => Self::UnrealShaderHeader,
      LanguageType::UrWeb => Self::UrWeb,
      LanguageType::UrWebProject => Self::UrWebProject,
      LanguageType::VB6 => Self::VB6,
      LanguageType::VBScript => Self::VBScript,
      LanguageType::Vala => Self::Vala,
      LanguageType::Velocity => Self::Velocity,
      LanguageType::Verilog => Self::Verilog,
      LanguageType::VerilogArgsFile => Self::VerilogArgsFile,
      LanguageType::Vhdl => Self::Vhdl,
      LanguageType::VimScript => Self::VimScript,
      LanguageType::VisualBasic => Self::VisualBasic,
      LanguageType::VisualStudioProject => Self::VisualStudioProject,
      LanguageType::VisualStudioSolution => Self::VisualStudioSolution,
      LanguageType::Vue => Self::Vue,
      LanguageType::WebAssembly => Self::WebAssembly,
      LanguageType::Wolfram => Self::Wolfram,
      LanguageType::XSL => Self::XSL,
      LanguageType::Xaml => Self::Xaml,
      LanguageType::XcodeConfig => Self::XcodeConfig,
      LanguageType::Xml => Self::Xml,
      LanguageType::Xtend => Self::Xtend,
      LanguageType::Yaml => Self::Yaml,
      LanguageType::Zig => Self::Zig,
      LanguageType::Zsh => Self::Zsh,
      _ => todo!(),
    }
  }
}
