use napi_derive::napi;

#[derive(Debug)]
#[napi(string_enum)]
pub enum LangType {
  ABNF,
  Abap,
  ActionScript,
  Ada,
  Agda,
  Alex,
  Alloy,
  Arduino,
  AsciiDoc,
  Asn1,
  Asp,
  AspNet,
  Assembly,
  AssemblyGAS,
  AutoHotKey,
  Autoconf,
  Automake,
  Bash,
  Batch,
  Bean,
  BrightScript,
  C,
  CHeader,
  CMake,
  CSharp,
  CShell,
  Cabal,
  Cassius,
  Ceylon,
  Clojure,
  ClojureC,
  ClojureScript,
  Cobol,
  CodeQL,
  CoffeeScript,
  Cogent,
  ColdFusion,
  ColdFusionScript,
  Coq,
  Cpp,
  CppHeader,
  Crystal,
  Css,
  D,
  Daml,
  Dart,
  DeviceTree,
  Dhall,
  Dockerfile,
  DotNetResource,
  DreamMaker,
  Dust,
  Edn,
  Elisp,
  Elixir,
  Elm,
  Elvish,
  EmacsDevEnv,
  Emojicode,
  Erlang,
  FEN,
  FSharp,
  Fish,
  FlatBuffers,
  Forth,
  FortranLegacy,
  FortranModern,
  FreeMarker,
  Fstar,
  Futhark,
  GDB,
  GdScript,
  Gherkin,
  Gleam,
  Glsl,
  Go,
  Gohtml,
  Graphql,
  Groovy,
  Gwion,
  Hamlet,
  Handlebars,
  Happy,
  Haskell,
  Haxe,
  Hcl,
  Headache,
  Hex,
  Hlsl,
  HolyC,
  Html,
  Idris,
  Ini,
  IntelHex,
  Isabelle,
  Jai,
  Java,
  JavaScript,
  Json,
  Jsonnet,
  Jsx,
  Julia,
  Julius,
  Jupyter,
  K,
  KakouneScript,
  Kotlin,
  LLVM,
  Lean,
  Less,
  LinkerScript,
  Liquid,
  Lisp,
  LiveScript,
  Logtalk,
  Lua,
  Lucius,
  Madlang,
  Makefile,
  Markdown,
  Meson,
  Mint,
  ModuleDef,
  MoonScript,
  MsBuild,
  Mustache,
  Nim,
  Nix,
  NotQuitePerl,
  OCaml,
  ObjectiveC,
  ObjectiveCpp,
  Odin,
  OpenType,
  Org,
  Oz,
  PSL,
  Pan,
  Pascal,
  Perl,
  Perl6,
  Pest,
  Php,
  Polly,
  Pony,
  PostCss,
  PowerShell,
  Processing,
  Prolog,
  Protobuf,
  Pug,
  PureScript,
  Python,
  Q,
  Qcl,
  Qml,
  R,
  RON,
  RPMSpecfile,
  Racket,
  Rakefile,
  Razor,
  ReStructuredText,
  Renpy,
  Ruby,
  RubyHtml,
  Rust,
  SRecode,
  Sass,
  Scala,
  Scheme,
  Scons,
  Sh,
  Sml,
  Solidity,
  SpecmanE,
  Spice,
  Sql,
  Stan,
  Stratego,
  Stylus,
  Svelte,
  Svg,
  Swift,
  Swig,
  SystemVerilog,
  Tcl,
  Tera,
  Tex,
  Text,
  Thrift,
  Toml,
  Tsx,
  Ttcn,
  Twig,
  TypeScript,
  UnrealDeveloperMarkdown,
  UnrealPlugin,
  UnrealProject,
  UnrealScript,
  UnrealShader,
  UnrealShaderHeader,
  UrWeb,
  UrWebProject,
  VB6,
  VBScript,
  Vala,
  Velocity,
  Verilog,
  VerilogArgsFile,
  Vhdl,
  VimScript,
  VisualBasic,
  VisualStudioProject,
  VisualStudioSolution,
  Vue,
  WebAssembly,
  Wolfram,
  XSL,
  Xaml,
  XcodeConfig,
  Xml,
  Xtend,
  Yaml,
  Zig,
  Zsh,
}

impl From<tokei::LanguageType> for LangType {
  fn from(language: tokei::LanguageType) -> Self {
    match language {
      tokei::LanguageType::ABNF => Self::ABNF,
      tokei::LanguageType::Abap => Self::Abap,
      tokei::LanguageType::ActionScript => Self::ActionScript,
      tokei::LanguageType::Ada => Self::Ada,
      tokei::LanguageType::Agda => Self::Agda,
      tokei::LanguageType::Alex => Self::Alex,
      tokei::LanguageType::Alloy => Self::Alloy,
      tokei::LanguageType::Arduino => Self::Arduino,
      tokei::LanguageType::AsciiDoc => Self::AsciiDoc,
      tokei::LanguageType::Asn1 => Self::Asn1,
      tokei::LanguageType::Asp => Self::Asp,
      tokei::LanguageType::AspNet => Self::AspNet,
      tokei::LanguageType::Assembly => Self::Assembly,
      tokei::LanguageType::AssemblyGAS => Self::AssemblyGAS,
      tokei::LanguageType::AutoHotKey => Self::AutoHotKey,
      tokei::LanguageType::Autoconf => Self::Autoconf,
      tokei::LanguageType::Automake => Self::Automake,
      tokei::LanguageType::Bash => Self::Bash,
      tokei::LanguageType::Batch => Self::Batch,
      tokei::LanguageType::Bean => Self::Bean,
      tokei::LanguageType::BrightScript => Self::BrightScript,
      tokei::LanguageType::C => Self::C,
      tokei::LanguageType::CHeader => Self::CHeader,
      tokei::LanguageType::CMake => Self::CMake,
      tokei::LanguageType::CSharp => Self::CSharp,
      tokei::LanguageType::CShell => Self::CShell,
      tokei::LanguageType::Cabal => Self::Cabal,
      tokei::LanguageType::Cassius => Self::Cassius,
      tokei::LanguageType::Ceylon => Self::Ceylon,
      tokei::LanguageType::Clojure => Self::Clojure,
      tokei::LanguageType::ClojureC => Self::ClojureC,
      tokei::LanguageType::ClojureScript => Self::ClojureScript,
      tokei::LanguageType::Cobol => Self::Cobol,
      tokei::LanguageType::CodeQL => Self::CodeQL,
      tokei::LanguageType::CoffeeScript => Self::CoffeeScript,
      tokei::LanguageType::Cogent => Self::Cogent,
      tokei::LanguageType::ColdFusion => Self::ColdFusion,
      tokei::LanguageType::ColdFusionScript => Self::ColdFusionScript,
      tokei::LanguageType::Coq => Self::Coq,
      tokei::LanguageType::Cpp => Self::Cpp,
      tokei::LanguageType::CppHeader => Self::CppHeader,
      tokei::LanguageType::Crystal => Self::Crystal,
      tokei::LanguageType::Css => Self::Css,
      tokei::LanguageType::D => Self::D,
      tokei::LanguageType::Daml => Self::Daml,
      tokei::LanguageType::Dart => Self::Dart,
      tokei::LanguageType::DeviceTree => Self::DeviceTree,
      tokei::LanguageType::Dhall => Self::Dhall,
      tokei::LanguageType::Dockerfile => Self::Dockerfile,
      tokei::LanguageType::DotNetResource => Self::DotNetResource,
      tokei::LanguageType::DreamMaker => Self::DreamMaker,
      tokei::LanguageType::Dust => Self::Dust,
      tokei::LanguageType::Edn => Self::Edn,
      tokei::LanguageType::Elisp => Self::Elisp,
      tokei::LanguageType::Elixir => Self::Elixir,
      tokei::LanguageType::Elm => Self::Elm,
      tokei::LanguageType::Elvish => Self::Elvish,
      tokei::LanguageType::EmacsDevEnv => Self::EmacsDevEnv,
      tokei::LanguageType::Emojicode => Self::Emojicode,
      tokei::LanguageType::Erlang => Self::Erlang,
      tokei::LanguageType::FEN => Self::FEN,
      tokei::LanguageType::FSharp => Self::FSharp,
      tokei::LanguageType::Fish => Self::Fish,
      tokei::LanguageType::FlatBuffers => Self::FlatBuffers,
      tokei::LanguageType::Forth => Self::Forth,
      tokei::LanguageType::FortranLegacy => Self::FortranLegacy,
      tokei::LanguageType::FortranModern => Self::FortranModern,
      tokei::LanguageType::FreeMarker => Self::FreeMarker,
      tokei::LanguageType::Fstar => Self::Fstar,
      tokei::LanguageType::Futhark => Self::Futhark,
      tokei::LanguageType::GDB => Self::GDB,
      tokei::LanguageType::GdScript => Self::GdScript,
      tokei::LanguageType::Gherkin => Self::Gherkin,
      tokei::LanguageType::Gleam => Self::Gleam,
      tokei::LanguageType::Glsl => Self::Glsl,
      tokei::LanguageType::Go => Self::Go,
      tokei::LanguageType::Gohtml => Self::Gohtml,
      tokei::LanguageType::Graphql => Self::Graphql,
      tokei::LanguageType::Groovy => Self::Groovy,
      tokei::LanguageType::Gwion => Self::Gwion,
      tokei::LanguageType::Hamlet => Self::Hamlet,
      tokei::LanguageType::Handlebars => Self::Handlebars,
      tokei::LanguageType::Happy => Self::Happy,
      tokei::LanguageType::Haskell => Self::Haskell,
      tokei::LanguageType::Haxe => Self::Haxe,
      tokei::LanguageType::Hcl => Self::Hcl,
      tokei::LanguageType::Headache => Self::Headache,
      tokei::LanguageType::Hex => Self::Hex,
      tokei::LanguageType::Hlsl => Self::Hlsl,
      tokei::LanguageType::HolyC => Self::HolyC,
      tokei::LanguageType::Html => Self::Html,
      tokei::LanguageType::Idris => Self::Idris,
      tokei::LanguageType::Ini => Self::Ini,
      tokei::LanguageType::IntelHex => Self::IntelHex,
      tokei::LanguageType::Isabelle => Self::Isabelle,
      tokei::LanguageType::Jai => Self::Jai,
      tokei::LanguageType::Java => Self::Java,
      tokei::LanguageType::JavaScript => Self::JavaScript,
      tokei::LanguageType::Json => Self::Json,
      tokei::LanguageType::Jsonnet => Self::Jsonnet,
      tokei::LanguageType::Jsx => Self::Jsx,
      tokei::LanguageType::Julia => Self::Julia,
      tokei::LanguageType::Julius => Self::Julius,
      tokei::LanguageType::Jupyter => Self::Jupyter,
      tokei::LanguageType::K => Self::K,
      tokei::LanguageType::KakouneScript => Self::KakouneScript,
      tokei::LanguageType::Kotlin => Self::Kotlin,
      tokei::LanguageType::LLVM => Self::LLVM,
      tokei::LanguageType::Lean => Self::Lean,
      tokei::LanguageType::Less => Self::Less,
      tokei::LanguageType::LinkerScript => Self::LinkerScript,
      tokei::LanguageType::Liquid => Self::Liquid,
      tokei::LanguageType::Lisp => Self::Lisp,
      tokei::LanguageType::LiveScript => Self::LiveScript,
      tokei::LanguageType::Logtalk => Self::Logtalk,
      tokei::LanguageType::Lua => Self::Lua,
      tokei::LanguageType::Lucius => Self::Lucius,
      tokei::LanguageType::Madlang => Self::Madlang,
      tokei::LanguageType::Makefile => Self::Makefile,
      tokei::LanguageType::Markdown => Self::Markdown,
      tokei::LanguageType::Meson => Self::Meson,
      tokei::LanguageType::Mint => Self::Mint,
      tokei::LanguageType::ModuleDef => Self::ModuleDef,
      tokei::LanguageType::MoonScript => Self::MoonScript,
      tokei::LanguageType::MsBuild => Self::MsBuild,
      tokei::LanguageType::Mustache => Self::Mustache,
      tokei::LanguageType::Nim => Self::Nim,
      tokei::LanguageType::Nix => Self::Nix,
      tokei::LanguageType::NotQuitePerl => Self::NotQuitePerl,
      tokei::LanguageType::OCaml => Self::OCaml,
      tokei::LanguageType::ObjectiveC => Self::ObjectiveC,
      tokei::LanguageType::ObjectiveCpp => Self::ObjectiveCpp,
      tokei::LanguageType::Odin => Self::Odin,
      tokei::LanguageType::OpenType => Self::OpenType,
      tokei::LanguageType::Org => Self::Org,
      tokei::LanguageType::Oz => Self::Oz,
      tokei::LanguageType::PSL => Self::PSL,
      tokei::LanguageType::Pan => Self::Pan,
      tokei::LanguageType::Pascal => Self::Pascal,
      tokei::LanguageType::Perl => Self::Perl,
      tokei::LanguageType::Perl6 => Self::Perl6,
      tokei::LanguageType::Pest => Self::Pest,
      tokei::LanguageType::Php => Self::Php,
      tokei::LanguageType::Polly => Self::Polly,
      tokei::LanguageType::Pony => Self::Pony,
      tokei::LanguageType::PostCss => Self::PostCss,
      tokei::LanguageType::PowerShell => Self::PowerShell,
      tokei::LanguageType::Processing => Self::Processing,
      tokei::LanguageType::Prolog => Self::Prolog,
      tokei::LanguageType::Protobuf => Self::Protobuf,
      tokei::LanguageType::Pug => Self::Pug,
      tokei::LanguageType::PureScript => Self::PureScript,
      tokei::LanguageType::Python => Self::Python,
      tokei::LanguageType::Q => Self::Q,
      tokei::LanguageType::Qcl => Self::Qcl,
      tokei::LanguageType::Qml => Self::Qml,
      tokei::LanguageType::R => Self::R,
      tokei::LanguageType::RON => Self::RON,
      tokei::LanguageType::RPMSpecfile => Self::RPMSpecfile,
      tokei::LanguageType::Racket => Self::Racket,
      tokei::LanguageType::Rakefile => Self::Rakefile,
      tokei::LanguageType::Razor => Self::Razor,
      tokei::LanguageType::ReStructuredText => Self::ReStructuredText,
      tokei::LanguageType::Renpy => Self::Renpy,
      tokei::LanguageType::Ruby => Self::Ruby,
      tokei::LanguageType::RubyHtml => Self::RubyHtml,
      tokei::LanguageType::Rust => Self::Rust,
      tokei::LanguageType::SRecode => Self::SRecode,
      tokei::LanguageType::Sass => Self::Sass,
      tokei::LanguageType::Scala => Self::Scala,
      tokei::LanguageType::Scheme => Self::Scheme,
      tokei::LanguageType::Scons => Self::Scons,
      tokei::LanguageType::Sh => Self::Sh,
      tokei::LanguageType::Sml => Self::Sml,
      tokei::LanguageType::Solidity => Self::Solidity,
      tokei::LanguageType::SpecmanE => Self::SpecmanE,
      tokei::LanguageType::Spice => Self::Spice,
      tokei::LanguageType::Sql => Self::Sql,
      tokei::LanguageType::Stan => Self::Stan,
      tokei::LanguageType::Stratego => Self::Stratego,
      tokei::LanguageType::Stylus => Self::Stylus,
      tokei::LanguageType::Svelte => Self::Svelte,
      tokei::LanguageType::Svg => Self::Svg,
      tokei::LanguageType::Swift => Self::Swift,
      tokei::LanguageType::Swig => Self::Swig,
      tokei::LanguageType::SystemVerilog => Self::SystemVerilog,
      tokei::LanguageType::Tcl => Self::Tcl,
      tokei::LanguageType::Tera => Self::Tera,
      tokei::LanguageType::Tex => Self::Tex,
      tokei::LanguageType::Text => Self::Text,
      tokei::LanguageType::Thrift => Self::Thrift,
      tokei::LanguageType::Toml => Self::Toml,
      tokei::LanguageType::Tsx => Self::Tsx,
      tokei::LanguageType::Ttcn => Self::Ttcn,
      tokei::LanguageType::Twig => Self::Twig,
      tokei::LanguageType::TypeScript => Self::TypeScript,
      tokei::LanguageType::UnrealDeveloperMarkdown => Self::UnrealDeveloperMarkdown,
      tokei::LanguageType::UnrealPlugin => Self::UnrealPlugin,
      tokei::LanguageType::UnrealProject => Self::UnrealProject,
      tokei::LanguageType::UnrealScript => Self::UnrealScript,
      tokei::LanguageType::UnrealShader => Self::UnrealShader,
      tokei::LanguageType::UnrealShaderHeader => Self::UnrealShaderHeader,
      tokei::LanguageType::UrWeb => Self::UrWeb,
      tokei::LanguageType::UrWebProject => Self::UrWebProject,
      tokei::LanguageType::VB6 => Self::VB6,
      tokei::LanguageType::VBScript => Self::VBScript,
      tokei::LanguageType::Vala => Self::Vala,
      tokei::LanguageType::Velocity => Self::Velocity,
      tokei::LanguageType::Verilog => Self::Verilog,
      tokei::LanguageType::VerilogArgsFile => Self::VerilogArgsFile,
      tokei::LanguageType::Vhdl => Self::Vhdl,
      tokei::LanguageType::VimScript => Self::VimScript,
      tokei::LanguageType::VisualBasic => Self::VisualBasic,
      tokei::LanguageType::VisualStudioProject => Self::VisualStudioProject,
      tokei::LanguageType::VisualStudioSolution => Self::VisualStudioSolution,
      tokei::LanguageType::Vue => Self::Vue,
      tokei::LanguageType::WebAssembly => Self::WebAssembly,
      tokei::LanguageType::Wolfram => Self::Wolfram,
      tokei::LanguageType::XSL => Self::XSL,
      tokei::LanguageType::Xaml => Self::Xaml,
      tokei::LanguageType::XcodeConfig => Self::XcodeConfig,
      tokei::LanguageType::Xml => Self::Xml,
      tokei::LanguageType::Xtend => Self::Xtend,
      tokei::LanguageType::Yaml => Self::Yaml,
      tokei::LanguageType::Zig => Self::Zig,
      tokei::LanguageType::Zsh => Self::Zsh,
      _ => todo!(),
    }
  }
}
