/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Diagnostic {
  fileName: string
  help: string
  url: string
  severity: string
  code: string
  message: string
  labels: Array<LabeledLoc>
}

export interface GlobJsArgs {
  pattern?: string
  ignore?: Array<string>
  cwd: string
}

export declare function innerDebugLint(oxlintConfig: string, globJsArgs: GlobJsArgs): Array<Diagnostic>

export declare function innerLint(globJsArgs: GlobJsArgs, category: NaPiCategory): Array<Diagnostic>

export interface LabeledLoc {
  span: Span
  loc: Location
}

export interface Location {
  start: Position
  end: Position
}

export declare const enum NaPiCategory {
  V20250601Inner = 0
}

export interface Position {
  line: number
  col: number
}

export interface Response {
  rc: string
  map: Record<string, number>
}

export interface Span {
  start: number
  end: number
}
