name: shined-doctor-engine-debug

permissions:
  contents: write
  id-token: write
# on:
#   push:
#     branches:
#       - main

on:
  push:
    tags:
      - "d*"

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Draft Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: |
          echo "RELEASE_ID: ${{ steps.create_release.outputs.id }}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          RELEASE_ID: ${{ steps.create_release.outputs.id }}

      - name: Update Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: false
          draft: false
          make_latest: true