name: shined-doctor-engine-debug
env:
permissions:
  contents: write
  id-token: write
on:
  push:
    branches:
      - main

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout
        run: |
          echo "RELEASE_ID: ${{ github.event.release.id }}"
        env:
          RELEASE_ID: ${{ github.event.release.id }}