name: debug
env:
  DEBUG: napi:*
  APP_NAME: engine
  MACOSX_DEPLOYMENT_TARGET: '10.13'
  CARGO_INCREMENTAL: '1'
  NAPI_DIR: napi/doctor-engine
permissions:
  contents: write
  id-token: write
on:
  push:
    branches:
      - main
  # release:
  #   types: [prereleased, published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          ## macos
          - host: macos-latest
            target: x86_64-apple-darwin
          - host: macos-latest
            target: aarch64-apple-darwin

          # windows x86_64
          - host: windows-latest
            target: x86_64-pc-windows-msvc
          - host: windows-latest
            target: aarch64-pc-windows-msvc

          # linux x86_64
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - host: ubuntu-latest
            target: x86_64-unknown-linux-musl
          
          #linux arm
          - host: ubuntu-22.04-arm
            target: aarch64-unknown-linux-gnu
          - host: ubuntu-22.04-arm
            target: aarch64-unknown-linux-musl
    
    name: stable - ${{ matrix.settings.target }} - node@20
    runs-on: ${{ matrix.settings.host }}


    defaults:
      run:
        working-directory: ${{ env.NAPI_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ls
        if: contains(matrix.settings.target, 'musl') && contains(matrix.settings.host, 'ubuntu')
        run: |
          ls -la /usr
          ls -la /usr/lib

      - name: Install musl tools
        if: contains(matrix.settings.target, 'musl') && contains(matrix.settings.host, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools gcc-aarch64-linux-gnu

      - name: ls2
        if: contains(matrix.settings.target, 'musl') && contains(matrix.settings.host, 'ubuntu')
        run: |
          ls -la /usr
          ls -la /usr/lib

      - name: Configure ARM64 musl linkage
        if: contains(matrix.settings.target, 'aarch64') && contains(matrix.settings.target, 'musl')
        run: |
          # 创建必要的目录和软链接
          sudo mkdir -p /usr/aarch64-linux-musl/lib/
          sudo ln -s /usr/aarch64-linux-gnu/lib/libgcc_s.so.1 /usr/aarch64-linux-musl/lib/libgcc_s.so.1
          # 设置环境变量指定链接器
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV


