name: shined-doctor-engine-release
env:
  DEBUG: napi:*
  APP_NAME: doctor
  MACOSX_DEPLOYMENT_TARGET: '10.13'
  CARGO_INCREMENTAL: '1'
  NAPI_DIR: napi/doctor_engine
permissions:
  contents: write
  id-token: write
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout
        run: |
          echo "RELEASE_ID: ${{ github.event.release.id }}"
        env:
          RELEASE_ID: ${{ github.event.release.id }}