name: shined-doctor-engine-debug

permissions:
  contents: write
  id-token: write
on:
  push:
    branches:
      - main

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Draft Release
        run: | 
          ldd --version
       