name: shined-doctor-engine-release
env:
  DEBUG: napi:*
  APP_NAME: doctor-engine
  MACOSX_DEPLOYMENT_TARGET: '10.13'
  CARGO_INCREMENTAL: '1'
permissions:
  contents: write
  id-token: write
on:
  push:
    branches:
      - main
  # release:
  #   types: [prereleased, published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          ## macos
          - host: macos-latest
            target: x86_64-apple-darwin
          - host: macos-latest
            target: aarch64-apple-darwin

          # windows x86_64
          - host: windows-latest
            target: x86_64-pc-windows-msvc
          - host: windows-latest
            target: aarch64-pc-windows-msvc

          # linux x86_64
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - host: ubuntu-latest
            target: x86_64-unknown-linux-musl
          
          #linux arm
          - host: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
          - host: ubuntu-24.04-arm
            target: aarch64-unknown-linux-musl
    
    name: stable - ${{ matrix.settings.target }} - node@20
    runs-on: ${{ matrix.settings.host }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: napi/doctor-engine/package-lock.json

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.settings.target }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build -- --target ${{ matrix.settings.target }}
        shell: bash
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: ${{ env.APP_NAME }}.*.node
          if-no-files-found: error


